app/reservation_management/urls.py
from django.urls import path
from app.reservation_management import views

app_name = 'reservation_management'

urlpatterns = [
    path('', views.ReservationListView.as_view(), name='reservation-list'),
    path('lesson/add', views.LessonAddView.as_view(), name='lesson-add'),
    path('lesson/list', views.LessonListView.as_view(), name='lesson-list'),
    path('lesson/<int:pk>/detail', views.LessonDetailView.as_view(), name='lesson-detail'),
    path('lesson/<int:pk>/update', views.LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/<int:pk>/delete', views.LessonDeleteView.as_view(), name='lesson-delete'),
    path('log-list', views.LogListView.as_view(), name='log-list'),
    path('feedback-list', views.FeedbackListView.as_view(), name='feedback-list'),
    path('send-feedback', views.ajax_send_feedback, name='send-feedback'),
    path('whats-new-confirm', views.ajax_whats_new_confirm, name='whats-new-confirm'),
]

app/reservation_tool_base_folder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app.reservation_tool_base_folder.views import HomepageView, HelpView

urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('help', HelpView.as_view(), name='help'),
    path('user/', include('user_management.urls')),
    path('reservation/', include('reservation_management.urls')),
]

if settings.ADMIN_ENABLED:
    urlpatterns.append(
        path('admin/', admin.site.urls)
    )

app/user_management/urls.py
from django.urls import path
from app.user_management import views
from django.contrib.auth import views as auth_views

app_name = 'user_management'

urlpatterns = [
    path('login', views.LoginUserView.as_view(), name='login'),
    path('registration', views.RegistrationView.as_view(), name='registration'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('list', views.UserListView.as_view(), name='list'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-check-email', views.ajax_check_email, name='ajax-check-email'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-check-username-is-correct', views.ajax_check_username_is_correct, name='ajax-check-username-is-correct'),
    path('ajax-check-unimore-credentials', views.ajax_check_unimore_credentials, name='ajax-check-unimore-credentials'),
    path('settings', views.SettingsView.as_view(), name='settings'),
    path('delete', views.UserDeleteView.as_view(), name='delete'),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('cookie-policy', views.CookiePolicyView.as_view(), name='cookie-policy'),
    path(
        'update-unimore-credentials',
        views.UserUpdateUnimoreCredentialsView.as_view(),
        name='update-unimore-credentials'
    ),
    path('greenpass-add', views.UserGreenPassAddView.as_view(), name='green-pass-add'),
    path('greenpass-delete', views.UserGreenPassDeleteView.as_view(), name='green-pass-delete'),
    path('general-settings', views.UserGeneralSettingsView.as_view(), name='general-settings'),

]

app/user_management/models.py
from cryptography.fernet import Fernet
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime


class PlatformUser(AbstractUser):
    AbstractUser._meta.get_field('email')._unique = True
    is_manager = models.BooleanField(default=False)

    unimore_username = models.CharField(max_length=500)
    unimore_password = models.CharField(max_length=500)
    credentials_ok = models.BooleanField(default=True)

    enable_automatic_reservation = models.BooleanField(default=True)
    feedback = models.BooleanField(default=True)
    whats_new = models.BooleanField(default=True)

    privacy_and_cookie_policy_acceptance = models.BooleanField(default=False)

    green_pass_link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.username

    @property
    def today_lessons(self):
        return self.lessons.filter(day=datetime.today().weekday())

    @property
    def lessons_count(self):
        return len(self.lessons.all())

    @property
    def plain_unimore_username(self):
        decryptor = Fernet(settings.CRYPTOGRAPHY_KEY.encode())
        return decryptor.decrypt(self.unimore_username.encode()).decode()

    @property
    def plain_unimore_password(self):
        decryptor = Fernet(settings.CRYPTOGRAPHY_KEY.encode())
        return decryptor.decrypt(self.unimore_password.encode()).decode()

app/user_management/views.py
from cryptography.fernet import Fernet
from django.conf import settings
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.views import LoginView
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_GET, require_POST
from django.views.generic import CreateView, TemplateView, DeleteView, ListView, UpdateView, FormView
from django.utils.translation import gettext_lazy as _

from app.reservation_tool_base_folder.decorators import not_authenticated_only
from app.user_management.check_unimore_credentials import check_unimore_credentials
from app.user_management.decorators import manager_required
from app.user_management.forms import LoginForm, PlatformUserCreationForm, UserUpdateUnimoreCredentialsForm, \
    UserAddGreenPass, UserGeneralSettings, UserDeleteGreenPass
from app.user_management.models import PlatformUser

account_activation_token = PasswordResetTokenGenerator()


@method_decorator(not_authenticated_only, name='dispatch')
class LoginUserView(LoginView):
    form_class = LoginForm
    template_name = 'registration/templates/registration/login.html'


@method_decorator(not_authenticated_only, name='dispatch')
class RegistrationView(CreateView):
    form_class = PlatformUserCreationForm
    template_name = 'registration/templates/registration/registration.html'
    success_url = reverse_lazy('user_management:email-verification-needed')

    def form_valid(self, form):
        self.object = form.save(commit=False)

        encryptor = Fernet(settings.CRYPTOGRAPHY_KEY.encode())
        self.object.unimore_username = encryptor.encrypt(self.object.unimore_username.encode()).decode()
        self.object.unimore_password = encryptor.encrypt(self.object.unimore_password.encode()).decode()

        response = super(RegistrationView, self).form_valid(form)

        mail_subject = _('Reservation Ninja - Confirm your email')
        relative_confirm_url = reverse(
            'user_management:verify-user-email',
            args=[
                urlsafe_base64_encode(force_bytes(self.object.pk)),
                account_activation_token.make_token(self.object)
            ]
        )

        self.object.email_user(
            subject=mail_subject,
            message=_(f'''Hi {self.object.username}, '''
                      + '''welcome to Reservation Ninja.\n'''
                      + '''\nClick this link to confirm your email:'''
                      + f'''\n{self.request.build_absolute_uri(relative_confirm_url)}\n'''
                      + '''\nSee you soon, \nReservation Ninja.''')
        )

        self.object.token_sent = True
        self.object.is_active = False
        self.object.save()

        return response


class UserGeneralSettingsView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserGeneralSettings
    template_name = 'user_management/templates/user_management/user_general_settings.html'
    success_url = reverse_lazy('user_management:settings')

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateUnimoreCredentialsView(LoginRequiredMixin, FormView):
    model = get_user_model()
    form_class = UserUpdateUnimoreCredentialsForm
    template_name = "user_management/templates/user_management/user_update_unimore_credentials.html"
    success_url = reverse_lazy('user_management:settings')

    def get_context_data(self, **kwargs):
        context = super(UserUpdateUnimoreCredentialsView, self).get_context_data(**kwargs)
        context['form'].fields['unimore_username'].widget.attrs.update({'value': self.request.user.plain_unimore_username})
        context['form'].fields['unimore_password'].widget.attrs.update({'value': ''})
        return context

    def form_valid(self, form):
        self.object = self.request.user

        username = form.cleaned_data['unimore_username']
        password = form.cleaned_data['unimore_password']

        encryptor = Fernet(settings.CRYPTOGRAPHY_KEY.encode())
        self.object.unimore_username = encryptor.encrypt(username.encode()).decode()
        self.object.unimore_password = encryptor.encrypt(password.encode()).decode()

        self.object.credentials_ok = True  # Credentials has been verified with Ajax before submit

        self.object.save()

        return super(UserUpdateUnimoreCredentialsView, self).form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user


class UserDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "user_management/templates/user_management/user_delete.html"
    success_url = reverse_lazy("home")
    model = get_user_model()

    def get_object(self, queryset=None):
        return self.request.user


@method_decorator(manager_required, name='dispatch')
class UserListView(ListView):
    model = get_user_model()
    template_name = "user_management/templates/user_management/user_list.html"

    def get_queryset(self):
        return get_user_model().objects.all().order_by('-date_joined')


class UserGreenPassAddView(LoginRequiredMixin, FormView):
    model = get_user_model()
    form_class = UserAddGreenPass
    template_name = "user_management/templates/user_management/greenpass_add.html"
    success_url = reverse_lazy("reservation_management:reservation-list")

    def form_valid(self, form):
        self.object = self.request.user

        self.object.green_pass_link = form.cleaned_data['green_pass_link']
        self.object.save()

        return super(UserGreenPassAddView, self).form_valid(form)


class UserGreenPassDeleteView(LoginRequiredMixin, FormView):
    form_class = UserDeleteGreenPass
    template_name = "user_management/templates/user_management/greenpass_delete.html"
    success_url = reverse_lazy("user_management:settings")

    def form_valid(self, form):
        self.object = self.request.user

        self.object.green_pass_link = None
        self.object.save()

        return super(UserGreenPassDeleteView, self).form_valid(form)


def user_login_by_token(request, user_id_b64=None, user_token=None):
    """
    Check the token is equal to one of user trying to verify its email.
    """
    try:
        uid = force_text(urlsafe_base64_decode(user_id_b64))
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, user_token):
        user.is_active = True
        user.save()
        login(request, user)
        return True

    return False


def verify_user_email(request, user_id_b64=None, user_token=None):
    """
    Check for the token and redirect to email verification succeeded page.
    """
    if not user_login_by_token(request, user_id_b64, user_token):
        message = _(f'Error. Attempt to validate email for the user {user_id_b64} with token {user_token}')
        subject = _('Authentication error')
        # in this case manager and admin are the same entity
        manager = PlatformUser.objects.get(is_manager=True)
        manager.email_user(subject=subject, message=message)
        # TODO: maybe provide an error message?
        return redirect('user_management:registration')

    return redirect('user_management:email-verified')


class PrivacyPolicyView(TemplateView):
    template_name = "user_management/templates/user_management/privacy_policy.html"


class CookiePolicyView(TemplateView):
    template_name = "user_management/templates/user_management/cookie-policy.html"


class EmailVerificationNeededView(TemplateView):
    template_name = 'user_management/templates/user_management/email_verification_needed.html'


class EmailVerifiedView(TemplateView):
    template_name = 'user_management/templates/user_management/email_verified.html'


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = "user_management/templates/user_management/settings.html"


def ajax_check_username_exists(request):
    return JsonResponse({'exists': True}) \
        if get_user_model().objects.filter(username=request.GET.get('username')).exists() \
        else JsonResponse({'exists': False})


def ajax_check_email(request):
    email = request.GET.get('email')

    if '@' in email and email.split('@')[1] == 'studenti.unimore.it':
        return JsonResponse({'is_unimore_email': True})
    return JsonResponse({'is_unimore_email': False})


@login_required
@require_GET
@csrf_protect
def ajax_check_username_is_correct(request):
    if request.GET.get('username') == request.user.username:
        return JsonResponse({'is_correct': True})
    return JsonResponse({'is_correct': False})


@login_required
@require_POST
@csrf_protect
def ajax_check_unimore_credentials(request):
    if not check_unimore_credentials(
            request.POST.get('username'), request.POST.get('password')
    ):
        return JsonResponse({'is_valid': False})
    return JsonResponse({'is_valid': True})

app/user_management/templates/user_management/cookie-policy.html
{% extends '../../../templates/base.html' %}

{% block title %}{{ block.super }} Cookie policy{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-12">
                <script id="CookieDeclaration"
                        src="https://consent.cookiebot.com/b02afbbd-fd14-425f-b4e0-26d7e488bbf8/cd.js"
                        type="text/javascript" async></script>
            </div>
        </div>
    </div>
{% endblock %}

app/user_management/templates/user_management/email_verification_needed.html
{% extends '../../../templates/base.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Email confirmation" %}{% endblock %}

{% block content %}
    <div class="row justify-content-center p-4">
        <div class="col-md-9 col-12">
            <h3 class="font-7 logo-font text-center site-color">{% translate "Check your email inbox." %}</h3>
            <h5 class="font-7 text-muted text-center logo-font">
                {% blocktranslate %}
                    You should have received a link to confirm your email.
                    If you have already confirmed it, you can login.
                {% endblocktranslate %}
            </h5>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-center ">
            <a class="btn site-btn font-7 w-50" href="{% url 'user_management:login' %}">Login</a>
        </div>
    </div>
{% endblock %}

app/user_management/templates/user_management/email_verified.html
{% extends '../../../templates/base.html' %}
{% load i18n %}

{% block extra_css %}
    <style>
        html,body {
            height: 100% !important;
            overflow: hidden;
        }
    </style>
{% endblock %}

{% block title %}{{ block.super }} {% translate "Email successfully verified" %}{% endblock %}

{% block content %}
    <div id="welcome-page-background" class="d-flex justify-content-center align-items-center column-flex">
        <div class="row">
            <div class="col site-col p-4">
                <h3 class="font-7 logo-font site-color big-text mb-3">{% translate "Welcome" %}</h3>
                <h5 class="font-5 logo-font">
                    {% translate "Your email has been successfully verified." %}
                    <a class="site-blue-text font-7 site-light-blue-text-mobile"
                       href="{% url 'reservation_management:reservation-list' %}">
                        {% translate "Join" %}
                    </a>.
                </h5>
            </div>
        </div>
    </div>
{% endblock %}

app/user_management/templates/user_management/greenpass_add.html
{% extends '../../../templates/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {% translate "Add Green Pass" %}{% endblock %}

{% block form_title %}{% translate "Add your Green Pass" %}{% endblock %}

{% block form_alert %}
    <div class="alert alert-danger" role="alert">
        <h5 class="alert-heading">{% translate "Warning" %} <i class="fas fa-exclamation-triangle"></i></h5>
        <p>
            <span class="font-6">
                {% translate "Make sure your drive link is accessible only by you." %}
            </span>
        </p>
        <hr>
        <p class="mb-0">
            {% blocktranslate %}
                Your file <strong>sharing policy</strong> on Google Drive have to be
                <strong>"With limitations"</strong> and you should be the <strong>only</strong>
                authorized user to access the file. <br>
                You can remove the Green Pass from <strong>your settings</strong>.
            {% endblocktranslate %}
        </p>
    </div>
{% endblock %}

{% block form_body %}
    {% crispy form %}
{% endblock %}

{% block back_url %}
    <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
        <i class="fas fa-chevron-left mr-2"></i>
        {% translate "Your reservations" %}
    </a>
{% endblock %}

app/user_management/templates/user_management/greenpass_delete.html
{% extends '../../../templates/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {% translate "Delete Green Pass" %}{% endblock %}

{% block form_title %}{% translate "Delete your Green Pass" %}{% endblock %}

{% block form_alert %}
    <div class="alert alert-danger" role="alert">
        <h5 class="alert-heading">{% translate "Warning" %} <i class="fas fa-exclamation-triangle"></i></h5>
        <p>
            <span class="font-6">
                {% translate "Are you sure you want to delete yuor Green Pass link?" %}
            </span>
        </p>
        <hr>
        <p class="mb-0">
            {% translate "This data will be destroyed and you will have to insert the link again." %}
        </p>
    </div>
{% endblock %}

{% block form_body %}
    {% crispy form %}
{% endblock %}

{% block back_url %}
    <a href="{% url 'user_management:settings' %}" class="font-6 site-blue-text">
        <i class="fas fa-chevron-left mr-2"></i>
        {% translate "Back to settings" %}
    </a>
{% endblock %}

{% block extra_javascript %}

{% endblock %}

app/user_management/templates/user_management/settings.html
{% extends '../../../templates/base.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Settings" %}{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <span class="h2 site-color logo-font">{% translate "Settings" %}</span>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex flex-column">
                <a href="{% url 'user_management:general-settings' %}"
                   class="site-link site-blue-text font-6">
                    {% translate "General settings" %}
                </a>
                <span class="text-muted font-5">{% translate "Update general settings" %}</span>
                <hr>
                <a href="{% url 'user_management:update-unimore-credentials' %}"
                   class="site-link site-blue-text font-6">
                    {% translate "Update Unimore credentials" %}
                </a>
                <span class="text-muted font-5">
                    {% blocktranslate %}
                        Update your Unimore credentials
                    {% endblocktranslate %}
                </span>
                <hr>
                {% if user.green_pass_link is not None %}
                    <a href="{% url 'user_management:green-pass-delete' %}"
                       class="site-link text-danger font-6">
                        {% translate "Delete your Green Pass" %}
                    </a>
                    <span class="text-muted font-5">
                    {% blocktranslate %}
                        Remove the link to your Green Pass
                    {% endblocktranslate %}
                </span>
                    <hr>
                {% endif %}
                <a href="{% url 'user_management:delete' %}"
                   class="site-link text-danger font-6">{% translate "Delete your account" %}</a>
                <span class="text-muted font-5">
                    {% blocktranslate %}
                        Delete your account and all your information
                    {% endblocktranslate %}
                </span>
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
                    <i class="fas fa-chevron-left mr-2"></i>
                    {% translate "Back home" %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

app/user_management/templates/user_management/user_ajax.html
{% load i18n %}

<script type="text/javascript">
    $('#id_username').on('change', function () {
        /**
         * Check if a username already exist.
         */
        $.ajax({
            type: 'GET',
            url: "{% url 'user_management:ajax-check-username-exists' %}",
            data: {
                'username': $(this).val(),
            },
            dataType: 'json',
            success: function(data) {
                let username_field = $('#id_username');

                if (data.exists) {
                    username_field.css('border-color', "#dc3545");
                    if (!$('#username-exists-error').length) {
                        username_field.after(
                            '<span id="username-exists-error" class="text-danger font-7 font-size-80">' +
                            '{% translate "Someone stole this username. Damn!." %}' +
                            '</span>'
                        );
                    }
                } else {
                    username_field.css('border-color', "#e8e8e8");
                    $('#username-exists-error').remove();
                }
            }
        });
    });

    $('#id_email').on('change', function () {
        /**
         * Check email conformity.
         */
        $.ajax({
            type: 'GET',
            url: "{% url 'user_management:ajax-check-email' %}",
            data: {
                'email': $(this).val(),
            },
            dataType: 'json',
            success: function(data) {
                let email_field = $('#id_email');

                if (!data.is_unimore_email) {
                    email_field.css('border-color', "#dc3545");
                    if (!$('#not-unimore-email').length) {
                        email_field.after(
                            '<span id="not-unimore-email" class="text-danger font-7 font-size-80">' +
                            '{% translate "Seems that you are not a Unimore student." %}' +
                            '</span>'
                        );
                    }
                } else {
                    email_field.css('border-color', "#e8e8e8");
                    $('#not-unimore-email').remove();
                }
            }
        });
    });

    $('#username-check').on('input', function () {
        /**
         * Check username is correct.
         */
        $.ajax({
            type: 'GET',
            url: "{% url 'user_management:ajax-check-username-is-correct' %}",
            data: {
                'username': $(this).val(),
            },
            dataType: 'json',
            success: function(data) {
                if (!data.is_correct)
                    $('#delete-user-submit').attr('disabled', true);
                else
                    $('#delete-user-submit').attr('disabled', false);
            }
        });
    });

    $("#check-unimore-credentials").on('click', function () {
        /**
         * Check unimore credentials to be correct.
         */
        let button = $(this);
        let resultDiv = $("#update-credentials-result-msg");
        $.ajax({
            type: 'POST',
            url: "{% url 'user_management:ajax-check-unimore-credentials' %}",
            data: {
                'username': $('#id_unimore_username').val(),
                'password': $('#id_unimore_password').val(),
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
                resultDiv.html('');
                button.attr("disabled", true);
                button.html(
                    '<div class="spinner-grow spinner-grow-sm mr-3" role="status"></div>' +
                    '<span>{% translate "Checking ..." %}</span>'
                );
            },
            success: function(data) {
                if (!data.is_valid) {
                    resultDiv.html(
                        '<div id="error-msg">' +
                            '<i class="fas fa-times site-color"></i>&nbsp;' +
                            '<span class="site-color font-7">' +
                            '{% translate "Either username or password are wrong. Please try again." %}' +
                            '</span>' +
                        '</div>'
                    );
                    button.html('{% translate "Update" %}')
                    button.attr("disabled", false);
                    window.setTimeout(function() {$('#error-msg').remove(); }, 2500);
                } else {
                    button.hide();
                    resultDiv.html(
                        '<i class="fas fa-check text-success"></i>&nbsp;' +
                        '<span class="text-success font-7">{% translate "Verified" %}</span>'
                    );
                    $("#submit-id-submit").attr("disabled", false);
                    $("#submit-id-submit").attr("name", "dummyName");  // With name 'submit' it doesn't work
                    $("#update-unimore-credentials-form").submit();
                }
            }
        });
    });
</script>

app/user_management/templates/user_management/user_delete.html
{% extends '../../../templates/base.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Delete account" %}{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <span class="h2 site-color logo-font">{% translate "Delete your account" %}</span>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <div class="alert alert-danger" role="alert">
                    <h5 class="alert-heading">{% translate "Warning" %} <i class="fas fa-exclamation-triangle"></i></h5>
                    <p>
                        <span class="font-6">
                            {% translate "Are you sure you want to delete your account?" %}
                        </span>
                    </p>
                    <hr>
                    <p class="mb-0">
                        {% translate "All your data will be destroyed and you won't be able to retrieve it." %}
                    </p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <form method="POST" class="d-flex flex-column"> {% csrf_token %}
                    <label>
                        <span class="small">
                            {% translate "For confirmation, enter your username:" %}
                        </span>
                        <span class="small text-muted font-6">{{ user.username }}</span>
                        <input id="username-check" type="text" class="form-control">
                    </label>
                    <input id="delete-user-submit"
                           class="btn site-btn"
                           type="submit"
                           value="{% translate 'Delete' %}"
                           disabled="disabled">
                </form>
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <a href="{% url 'user_management:settings' %}" class="font-6 site-blue-text">
                    <i class="fas fa-chevron-left mr-2"></i>
                    {% translate "Back to settings" %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'user_management/user_ajax.html' %}
{% endblock %}

app/user_management/templates/user_management/user_general_settings.html
{% extends '../../../templates/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {% translate "General settings" %}{% endblock %}

{% block form_title %}{% translate "General settings" %}{% endblock %}

{% block form_body %}
    {% crispy form %}
{% endblock %}

{% block back_url %}
    <a href="{% url 'user_management:settings' %}" class="font-6 site-blue-text">
        <i class="fas fa-chevron-left mr-2"></i>
        {% translate "Back to settings" %}
    </a>
{% endblock %}