reservation_management/urls.py
from django.urls import path
from reservation_management import views

app_name = 'reservation_management'

urlpatterns = [
    path('', views.ReservationListView.as_view(), name='reservation-list'),
    path('lesson/add', views.LessonAddView.as_view(), name='lesson-add'),
    path('lesson/list', views.LessonListView.as_view(), name='lesson-list'),
    path('lesson/<int:pk>/detail', views.LessonDetailView.as_view(), name='lesson-detail'),
    path('lesson/<int:pk>/update', views.LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/<int:pk>/delete', views.LessonDeleteView.as_view(), name='lesson-delete'),
    path('lesson-timetable', views.LessonTimetableView.as_view(), name='lesson-timetable'),
    path('lesson-overlap-error', views.LessonOverlapErrorView.as_view(), name='lesson-overlap-error'),
    path('no-lessons-error', views.NoLessonsErrorView.as_view(), name='no-lessons-error'),
    path('whats-new-confirm', views.ajax_whats_new_confirm, name='whats-new-confirm'),
    path('instagram-confirm', views.ajax_instagram_confirm, name='instagram-confirm'),
]

reservation_management/templates/reservation_management/lesson_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load app_filters %}

{% block title %}{{ block.super }} {% translate "Lesson" %}{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between align-items-center">
                {% url 'reservation_management:lesson-timetable' as time_table_url %}
                {% if time_table_url in request.META.HTTP_REFERER %}
                    <a href="{{ time_table_url }}" class="font-6 site-blue-text">
                        <i class="fas fa-chevron-left mr-2"></i>
                        {% translate "Your time table" %}
                    </a>
                {% else %}
                    <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 site-blue-text">
                        <i class="fas fa-chevron-left mr-2"></i>
                        {% translate "Your lessons" %}
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <div class="row">
                    <div class="col d-flex flex-column">
                        <span class="text-muted font-5">{{ lesson.day|get_day_from_int }}</span>
                        {% if lesson.name %}
                            <div>
                                <h2 class="font-7 logo-font" style="color: {{ lesson.color }};">{{ lesson.name }}</h2>
                            </div>
                            <div>
                                <span class="font-6">{{ lesson.classroom.name }}</span> -
                                <span class="font-6">{{ lesson.classroom.building.name }}</span>
                            </div>
                        {% else %}
                            <h2 class="font-7 logo-font"
                                style="color: {{ lesson.color }};">{{ lesson.classroom.name }}</h2>
                            <span class="font-6">{{ lesson.classroom.building.name }}</span>
                        {% endif %}
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'reservation_management:lesson-update' lesson.pk %}"
                           class="site-link no-decoration">
                            <i class="fas fa-pen mt-2 mr-3"></i>
                        </a>
                        <a href="{% url 'reservation_management:lesson-delete' lesson.pk %}"
                           class="site-link no-decoration">
                            <i class="fas fa-trash text-danger"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <ul>
                    <li>{% translate "Start at " %}{{ lesson.start_time }}</li>
                    <li>{% translate "End at " %}{{ lesson.end_time }}</li>
                </ul>
                <p>

                </p>
            </div>
        </div>
    </div>
{% endblock %}

reservation_management/templates/reservation_management/lesson_list.html
{% extends 'reservation_management/base/base_list.html' %}
{% load static %}
{% load i18n %}
{% load app_filters %}

{% block title %}
    {{ block.super }} {% translate 'My lessons' %}
{% endblock %}

{% block list_title %}
    {% translate 'Your lessons' %}
{% endblock %}

{% block list_button %}
    <div class="row justify-content-center">
        <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between align-items-center">
            <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
                <i class="fas fa-chevron-left mr-2"></i>
                {% translate "Your reservations" %}
            </a>
            <a href="{% url "reservation_management:lesson-add" %}"
               class="btn site-btn font-5" style="width: auto !important;">
                <i class="fas fa-plus"></i>
            </a>
        </div>
    </div>
{% endblock %}

{% block list_body %}
    {% for lesson in lesson_list %}
        <a href="{% url 'reservation_management:lesson-detail' lesson.pk %}"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/calendar.png' %}" alt="cal" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div class="text-wrap">
                    {% if lesson.name %}
                        <h6 class="mb-0">{{ lesson.name }} </h6>
                        <p class="mb-0 opacity-75 font-size-80 font-4">
                            {{ lesson.start_time }} - {{ lesson.end_time }}
                        </p>
                        <p class="mb-0 opacity-75">
                            {{ lesson.classroom.name }} - {{ lesson.classroom.building }}</p>
                    {% else %}
                        <h6 class="mb-0">{{ lesson.classroom }}</h6>
                        <p class="mb-0 opacity-75 font-size-80 font-4">
                            {{ lesson.start_time }} - {{ lesson.end_time }}
                        </p>
                        <p class="mb-0 opacity-75">
                            {{ lesson.classroom.building }}</p>
                    {% endif %}
                </div>
                <small class="opacity-50 text-nowrap">{{ lesson.day|get_day_from_int }}</small>
            </div>
        </a>
    {% empty %}
        <a href="{{ reservation.link }}"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/empty.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-2">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{% translate "No lesson here, insert your lessons!" %}</h6>
                    <p class="mb-0 opacity-75">
                        {% blocktranslate %}
                            Click the <strong>button</strong> and add them!
                        {% endblocktranslate %}
                    </p>
                </div>
                <small class="opacity-50 text-nowrap"></small>
            </div>
        </a>
    {% endfor %}
{% endblock %}

reservation_management/templates/reservation_management/lesson_overlap_error.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Error" %}{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center mt-3">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <h2 class="site-color logo-font">{% translate "Error: Lessons overlap!" %}</h2>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex flex-column">
                <div class="alert alert-danger" role="alert">
                    <h5 class="alert-heading">{% translate "Error" %} <i class="fas fa-exclamation-triangle"></i></h5>
                    <p>
                        <span class="font-6">
                            {% translate "A lessons overlap error was found." %}
                        </span>
                    </p>
                    <hr>
                    <p class="mb-0">
                        {% blocktranslate %}
                            Please, check your <strong>lessons</strong>.
                            You have <strong>at least</strong> two of them which <strong>times overlap</strong>.
                            <br><br>
                            In this case the lessons timetable <strong>can't work properly</strong>.
                        {% endblocktranslate %}
                    </p>
                    <p class="mt-4">
                         <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 btn btn-danger">
                            {% translate "Your lessons" %}
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

reservation_management/templates/reservation_management/lesson_timetable.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Timetable" %}{% endblock %}

{% block extra_css %}
    <style>
        table {
            table-layout: fixed;
            min-width: 1200px !important;
            margin-right: 10px;
        }

        table tr th:first-child {
            width: 200px !important;
        }

        .table-col {
            overflow-x: scroll;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center mt-5">
            <div class="col-md-10 col-12 d-flex justify-content-between align-items-center">
                <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
                    <i class="fas fa-chevron-left mr-2"></i>
                    {% translate "Your reservations" %}
                </a>
            </div>
        </div>
        <div class="row justify-content-center mt-3 mb-5">
            <div class="col-md-10 col-12">
                <h2 class="logo-font font-7 site-color">{% translate "Lessons timetable" %}</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-10 col-12 table-col">
                <table class="table table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col"></th>
                        <th scope="col">{% translate "Monday" %}</th>
                        <th scope="col">{% translate "Tuesday" %}</th>
                        <th scope="col">{% translate "Wednesday" %}</th>
                        <th scope="col">{% translate "Thursday" %}</th>
                        <th scope="col">{% translate "Friday" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for index, monday, tuesday, wednesday, thursday, friday in df.itertuples %}
                        <tr class="text-break text-center">
                            <th scope="row" class="font-5">
                                <div class="d-flex align-items-center h-100">
                                    {{ index }}
                                </div>
                            </th>
                            <td>
                                {% if monday %}
                                    {% include 'reservation_management/base/base_timetable_lesson.html' with lesson=monday %}
                                {% endif %}
                            </td>
                            <td>
                                {% if tuesday %}
                                    {% include 'reservation_management/base/base_timetable_lesson.html' with lesson=tuesday %}
                                {% endif %}
                            </td>
                            <td>
                                {% if wednesday %}
                                    {% include 'reservation_management/base/base_timetable_lesson.html' with lesson=wednesday %}
                                {% endif %}
                            </td>
                            <td>
                                {% if thursday %}
                                    {% include 'reservation_management/base/base_timetable_lesson.html' with lesson=thursday %}
                                {% endif %}
                            </td>
                            <td>
                                {% if friday %}
                                    {% include 'reservation_management/base/base_timetable_lesson.html' with lesson=friday %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

reservation_management/templates/reservation_management/no_lessons_error.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Error" %}{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center mt-3">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <h2 class="site-color logo-font">{% translate "Error: Lessons overlap!" %}</h2>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex flex-column">
                <div class="alert alert-danger" role="alert">
                    <h5 class="alert-heading">{% translate "Error" %} <i class="fas fa-exclamation-triangle"></i></h5>
                    <p>
                        <span class="font-6">
                            {% translate "A no lessons error was found." %}
                        </span>
                    </p>
                    <hr>
                    <p class="mb-0">
                        {% blocktranslate %}
                            Please, check your <strong>lessons</strong>.
                            You must have <strong>at least</strong> one lesson in your profile in order to see it.
                            <br><br>
                            In this case the lessons timetable <strong>can't work properly</strong>.
                        {% endblocktranslate %}
                    </p>
                    <p class="mt-4">
                         <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 btn btn-danger">
                            {% translate "Your lessons" %}
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

reservation_management/templates/reservation_management/reservation_ajax.html
{% load i18n %}

<script type="text/javascript">
    function send_feedback(ok, $button_clicked) {
        /**
         * Save user Feedback.
         */
        $.ajax({
            type: 'POST',
            url: "{% url 'analytics_management:send-feedback' %}",
            data: {
                'response_ok': ok,
            },
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
            beforeSend: function() {
                $("#feedback-response-yes").attr("disabled", true);
                $("#feedback-response-no").attr("disabled", true);
                $button_clicked.html(
                    '<div class="spinner-grow spinner-grow-sm mr-3" role="status"></div>' +
                    '<span>{% translate "Saving ..." %}</span>'
                );
            },
            success: function(data) {
                $('#user-feedback-box').html(
                    '<i class="fas fa-check text-success mr-3"></i>' +
                    '<span class="text-success font-6">{% translate "Thanks for the feedback!" %}</span><br>' +
                    '<span class="font-6 font-italic">Arigatō</span>'
                );
                window.setTimeout(function() {
                    $('#user-feedback-box').parent().remove();
                }, 3000);
            }
        });
    }

    $("#whats-new-confirm-button").on('click', function () {
        /**
         * After closing What's new modal, set whats_new=False on user to not show it anymore.
         */
        $.ajax({
            type: 'POST',
            url: "{% url 'reservation_management:whats-new-confirm' %}",
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
        });
    });

    $("#instagram-confirm-button").on('click', function () {
        /**
         * After closing Instagram modal, set instagram=False on user to not show it anymore.
         */
        $.ajax({
            type: 'POST',
            url: "{% url 'reservation_management:instagram-confirm' %}",
            headers:{
                "X-CSRFToken": '{{ csrf_token }}'
            },
            dataType: 'json',
        });
    });
</script>

reservation_management/templates/reservation_management/reservation_list.html
{% extends 'reservation_management/base/base_list.html' %}
{% load static %}
{% load i18n %}
{% load app_filters %}

{% block title %}
    {{ block.super }} {% translate 'My lessons' %}
{% endblock %}

{% block list_title %}
    {% translate "Your reservations" %}
{% endblock %}

{% block list_button %}
    <div class="row justify-content-center">
        <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between">
            <a href="{% url 'reservation_management:lesson-timetable' %}" class="btn btn-info mr-5 d-flex align-items-center"
               style="width: auto !important;">
                <i class="fas fa-clock"></i>
            </a>
            {% if user.green_pass_link is not None %}
                <a href="{{ user.green_pass_link }}" target="_blank" class="btn green-btn font-5">
                    <i class="fas fa-passport mr-2"></i>
                    {% translate "Green Pass" %}
                </a>
            {% else %}
                <a href="{% url 'user_management:green-pass-add' %}" class="btn green-btn font-5">
                    <i class="fas fa-passport mr-2"></i>
                    {% translate "Add your Green Pass" %}
                </a>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block list_body %}
    {% for reservation in reservation_list %}
        <a href="{{ reservation.link }}" target="_blank"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/reservation.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{{ reservation.lesson.classroom }} {{ reservation.lesson.start_time }}
                        - {{ reservation.lesson.end_time }}</h6>
                    <p class="mb-0 opacity-75">
                        {{ reservation.lesson.classroom.building }}</p>
                </div>
                <small class="opacity-50 text-nowrap">{{ reservation.lesson.day|get_day_from_int }}</small>
            </div>
        </a>
    {% empty %}
        {% if user.lessons.count == 0 %}
            <a href="{% url 'reservation_management:lesson-add' %}"
               class="list-group-item list-group-item-action d-flex gap-3 py-3"
               aria-current="true">
                <img src="{% static 'img/empty.png' %}" alt="res" width="32" height="32"
                     class="flex-shrink-0 mr-3">
                <div class="d-flex gap-2 w-100 justify-content-between">
                    <div>
                        <h6 class="mb-0">{% translate "No reservation made, insert your lessons!" %}</h6>
                        <p class="mb-0 opacity-75">
                            {% blocktranslate %}
                                Add your <strong>first lesson</strong> clicking the button below!
                            {% endblocktranslate %}
                        </p>
                    </div>
                    <small class="opacity-50 text-nowrap"></small>
                </div>
            </a>
        {% else %}
            <a href="#"
               class="list-group-item list-group-item-action d-flex gap-3 py-3"
               aria-current="true">
                <img src="{% static 'img/empty.png' %}" alt="res" width="32" height="32"
                     class="flex-shrink-0 mr-3">
                <div class="d-flex gap-2 w-100 justify-content-between">
                    <div>
                        <h6 class="mb-0">{% translate "Hooray! No reservations today." %}</h6>
                        <p class="mb-0 opacity-75">
                            {% blocktranslate %}
                                You can <strong>take it easy!</strong>
                            {% endblocktranslate %}
                        </p>
                    </div>
                    <small class="opacity-50 text-nowrap"></small>
                </div>
            </a>
        {% endif %}
    {% endfor %}
{% endblock %}

{% block extra_content %}
    {% include 'whats_new_modal.html' %}
    {% if not user.feedback and user.ask_for_feedback %}
        <div class="row justify-content-center align-items-center mt-3 mb-5">
            <div id="user-feedback-box"
                 class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex column-flex align-items-center justify-content-center">
                <span class="font-6">
                    {% translate "Are your reservations correct?" %}
                </span>
                <span class="small text-muted">
                    {% translate "You can disable daily feedbacks from settings" %}
                </span>
                <div class="mt-3 w-100 d-flex justify-content-center align-items-center">
                    <button id="feedback-response-yes" class="btn btn-outline-success mr-3 font-size-80 w-25">
                        {% translate "Yes" %}
                    </button>
                    <button id="feedback-response-no" class="btn btn-outline-danger font-size-80 w-25">
                        {% translate "No" %}
                    </button>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block bottom_nav_button %}
    {% if user.lessons.count > 0 %}
        <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 site-blue-text">
            {% translate "Your lessons" %}
            <i class="fas fa-chevron-right ml-2"></i>
        </a>
    {% else %}
        <a href="{% url 'reservation_management:lesson-add' %}" class="font-7 btn green-btn-outline">
            {% translate "+ Add your first lesson" %}
        </a>
    {% endif %}
{% endblock %}

{% block manager_tools %}
    {% if user.is_manager %}
        <div class="row justify-content-center mt-5 px-3">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex flex-column border p-4">
                <span class="h4 font-6 logo-font">Administration</span>
                <a href="{% url 'analytics_management:user-list' %}" class="site-link site-color font-6">
                    Users
                </a>
                <a href="{% url 'analytics_management:log-list' %}" class="site-link site-color font-6">
                    Logs
                </a>
                <a href="{% url 'analytics_management:feedback-list' %}" class="site-link site-color font-6">
                    Feedbacks
                </a>
                <a href="{% url 'analytics_management:stats' %}" class="site-link site-color font-6">
                    Stats
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block extra_javascript %}
    <script type="text/javascript">
        $(function () {
            $("#feedback-response-yes").on('click', function () {
                send_feedback(1, $(this));
            });

            $("#feedback-response-no").on('click', function () {
                send_feedback(0, $(this));
            });

            {% if user.whats_new %}
                $('#whats-new-modal').modal('show');
            {% endif %}
        });
    </script>
    {% include 'reservation_management/reservation_ajax.html' %}
{% endblock %}