app/reservation_management/urls.py
from django.urls import path
from app.reservation_management import views

app_name = 'reservation_management'

urlpatterns = [
    path('', views.ReservationListView.as_view(), name='reservation-list'),
    path('lesson/add', views.LessonAddView.as_view(), name='lesson-add'),
    path('lesson/list', views.LessonListView.as_view(), name='lesson-list'),
    path('lesson/<int:pk>/detail', views.LessonDetailView.as_view(), name='lesson-detail'),
    path('lesson/<int:pk>/update', views.LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/<int:pk>/delete', views.LessonDeleteView.as_view(), name='lesson-delete'),
    path('log-list', views.LogListView.as_view(), name='log-list'),
    path('feedback-list', views.FeedbackListView.as_view(), name='feedback-list'),
    path('send-feedback', views.ajax_send_feedback, name='send-feedback'),
    path('whats-new-confirm', views.ajax_whats_new_confirm, name='whats-new-confirm'),
]

app/reservation_tool_base_folder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app.reservation_tool_base_folder.views import HomepageView, HelpView

urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('help', HelpView.as_view(), name='help'),
    path('user/', include('user_management.urls')),
    path('reservation/', include('reservation_management.urls')),
]

if settings.ADMIN_ENABLED:
    urlpatterns.append(
        path('admin/', admin.site.urls)
    )

app/user_management/urls.py
from django.urls import path
from app.user_management import views
from django.contrib.auth import views as auth_views

app_name = 'user_management'

urlpatterns = [
    path('login', views.LoginUserView.as_view(), name='login'),
    path('registration', views.RegistrationView.as_view(), name='registration'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('list', views.UserListView.as_view(), name='list'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-check-email', views.ajax_check_email, name='ajax-check-email'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-check-username-is-correct', views.ajax_check_username_is_correct, name='ajax-check-username-is-correct'),
    path('ajax-check-unimore-credentials', views.ajax_check_unimore_credentials, name='ajax-check-unimore-credentials'),
    path('settings', views.SettingsView.as_view(), name='settings'),
    path('delete', views.UserDeleteView.as_view(), name='delete'),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('cookie-policy', views.CookiePolicyView.as_view(), name='cookie-policy'),
    path(
        'update-unimore-credentials',
        views.UserUpdateUnimoreCredentialsView.as_view(),
        name='update-unimore-credentials'
    ),
    path('greenpass-add', views.UserGreenPassAddView.as_view(), name='green-pass-add'),
    path('greenpass-delete', views.UserGreenPassDeleteView.as_view(), name='green-pass-delete'),
    path('general-settings', views.UserGeneralSettingsView.as_view(), name='general-settings'),

]

app/reservation_management/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _


class Building(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Classroom(models.Model):
    name = models.CharField(max_length=100)
    building = models.ForeignKey(Building, on_delete=models.CASCADE, related_name='classrooms')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['building__name', 'name']


class Lesson(models.Model):
    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    WEEKDAYS = [
        (MONDAY, _("Monday")),
        (TUESDAY, _("Tuesday")),
        (WEDNESDAY, _("Wednesday")),
        (THURSDAY, _("Thursday")),
        (FRIDAY, _("Friday")),
    ]
    day = models.PositiveSmallIntegerField(choices=WEEKDAYS, default=MONDAY)
    start_time = models.TimeField()
    end_time = models.TimeField()

    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE, related_name='lessons')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='lessons')

    def __str__(self):
        return (
            f'{self.user} in {self.classroom.name} - '
            f'{self.start_time.strftime("%H:%M")}/{self.end_time.strftime("%H:%M")} '
            f'on day {self.day}'
        )

    def clean(self):
        if self.start_time >= self.end_time:
            raise ValidationError(_('Lesson start time should be before end time'))
        return super(Lesson, self).clean()

    class Meta:
        ordering = ['day', 'start_time']


class Reservation(models.Model):
    link = models.URLField()
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='reservations')
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)

    def __str__(self):
        return (
            f'{self.lesson.classroom.name} of {self.lesson.user.username} '
            f'from {self.lesson.start_time} to {self.lesson.end_time}'
        )

    class Meta:
        ordering = ['start_time', 'end_time']


class Log(models.Model):
    execution_time = models.FloatField()
    users = models.IntegerField()
    lessons = models.IntegerField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.date}"

    @property
    def average_user_execution_time(self):
        return self.execution_time / self.users if self.users > 0 else 0

    @property
    def average_lesson_execution_time(self):
        return self.execution_time / self.lessons if self.lessons > 0 else 0


class Feedback(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='feedbacks', null=True)
    ok = models.BooleanField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} {self.ok}'

app/reservation_management/forms.py
from crispy_forms.helper import FormHelper
from django.utils.translation import gettext_lazy as _
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms

from app.reservation_management.models import Lesson

"""
per i giorni della settimana fornire in input una lista, lato server tradurre i giorni in numero.
ottenere questo con un dizionario, ad ogni giorno della settimana (chiave), è associato il corrispettivo indice 
numerico (valore) 
"""


class LessonForm(forms.ModelForm):
    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper.layout = Layout(
            Row(
                Column('day', css_class='form-group mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('start_time', css_class='form-group'),
                Column('end_time', css_class='form-group'),
                css_class='form-row',
            ),
            Row(
                Column('classroom', css_class='form-group mb-0'),
                Column(
                    Submit('submit', _('Insert'), css_class="btn site-btn mb-3 w-75 font-5"),
                    css_class='d-flex align-items-end justify-content-end'
                ),
                css_class='form-row '
            ),
        )

    class Meta:
        model = Lesson
        fields = (
            "day",
            "start_time",
            "end_time",
            "classroom",
        )
        labels = {
            'day': _('Day'),
            'start_time': _('Start time'),
            'end_time': _('End time'),
            'classroom': _('Classroom'),

        }
        widgets = {
            'day': forms.Select(attrs={'class': 'selectpicker', 'data-live-search': 'true'}),
            'classroom': forms.Select(attrs={'class': 'selectpicker', 'data-live-search': 'true'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
            'end_time': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
        }

app/reservation_management/views.py
from collections import defaultdict

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from app.reservation_management.decorators import lesson_owner_only
from app.reservation_management.forms import LessonForm
from app.reservation_management.models import Lesson, Reservation, Log, Feedback
from app.user_management.decorators import manager_required


class LessonAddView(LoginRequiredMixin, CreateView):
    model = Lesson
    form_class = LessonForm
    template_name = "reservation_management/templates/reservation_management/lesson_add.html"
    success_url = reverse_lazy("reservation_management:lesson-list")

    def post(self, request, *args, **kwargs):
        """
        In order to manage the cancel button from the lesson form. If 'cancel'
        is in the request.POST, the lesson must not be created.
        :return: HTTP response.
        """
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse_lazy("home"))
        else:
            return super(LessonAddView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(LessonAddView, self).form_valid(form)


class LessonListView(LoginRequiredMixin, ListView):
    """
    View to display the Lessons created by a user.
    """
    model = Lesson
    template_name = "reservation_management/templates/reservation_management/lesson_list.html"

    def get_queryset(self):
        return Lesson.objects.filter(user=self.request.user)


@method_decorator((login_required, lesson_owner_only), name='dispatch')
class LessonDetailView(DetailView):
    """
    View to show detail of a Lesson.
    """
    model = Lesson
    template_name = "reservation_management/templates/reservation_management/lesson_detail.html"


@method_decorator((login_required, lesson_owner_only), name='dispatch')
class LessonUpdateView(UpdateView):
    """
    View to update a Lesson.
    """
    model = Lesson
    form_class = LessonForm
    template_name = "reservation_management/templates/reservation_management/lesson_update.html"

    def get_success_url(self):
        return reverse_lazy("reservation_management:lesson-detail", kwargs={'pk': self.kwargs['pk']})


@method_decorator((login_required, lesson_owner_only), name='dispatch')
class LessonDeleteView(DeleteView):
    """
    View to delete an existing dish.
    """
    model = Lesson
    template_name = 'reservation_management/templates/reservation_management/lesson_delete.html'
    success_url = reverse_lazy('reservation_management:lesson-list')


class ReservationListView(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = "reservation_management/templates/reservation_management/reservation_list.html"

    def get_queryset(self):
        return Reservation.objects.filter(lesson__user=self.request.user)


@method_decorator(manager_required, name='dispatch')
class LogListView(ListView):
    model = Log
    template_name = "reservation_management/templates/reservation_management/log_list.html"

    def get_queryset(self):
        return Log.objects.all().order_by('-date')


@method_decorator(manager_required, name='dispatch')
class FeedbackListView(ListView):
    model = Feedback
    template_name = "reservation_management/templates/reservation_management/feedback_list.html"

    def get_queryset(self):
        feedbacks = Feedback.objects.all().order_by('-date', 'user')
        feedbacks_grouped_by_date = defaultdict(list)

        for feedback in feedbacks:
            feedbacks_grouped_by_date[feedback.date].append(feedback)

        # Dict cast is needed, because template see defaultdict as empty
        return dict(feedbacks_grouped_by_date)


@login_required
@require_POST
@csrf_protect
def ajax_send_feedback(request):
    user = request.user

    Feedback.objects.create(
        user=user,
        ok=int(request.POST.get('response_ok')) == 1,
    )

    user.feedback = True
    user.save()

    return JsonResponse({'ok': True})


@login_required
@require_POST
@csrf_protect
def ajax_whats_new_confirm(request):
    user = request.user
    user.whats_new = False
    user.save()

    return JsonResponse({'ok', True})

app/reservation_management/templates/reservation_management/feedback_list.html
{% extends '../../../templates/base.html' %}

{% block title %}Feedbacks{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between align-items-center">
                <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
                    <i class="fas fa-chevron-left mr-2"></i>
                    Back
                </a>
            </div>
        </div>
        <div class="row justify-content-center mb-5 mt-3">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <h2 class="logo-font site-color">Feedbacks</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                {% for date, feedbacks in object_list.items %}
                    <div class="mb-4">
                        <span class="font-6">{{ date }}</span>
                        <div class="list-group mt-2">
                            {% for feedback in feedbacks %}
                                <div class="list-group-item py-3">
                                    <span>{{ feedback.user.username }}</span> -
                                    {% if feedback.ok %}
                                        <span class="font-6 text-success">{{ feedback.ok }}</span>
                                    {% else %}
                                        <span class="font-6 text-danger">{{ feedback.ok }}</span>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app/reservation_management/templates/reservation_management/lesson_add.html
{% extends '../../../templates/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {% translate "Add a lesson" %}{% endblock %}

{% block form_title %}{% translate "Add a lesson" %}{% endblock %}

{% block form_body %}
    {% crispy form %}
{% endblock %}

{% block back_url %}
    <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 site-blue-text">
        <i class="fas fa-chevron-left mr-2"></i>
        {% translate "Your lessons" %}
    </a>
{% endblock %}

app/reservation_management/templates/reservation_management/lesson_delete.html
{% extends '../../../templates/base_form.html' %}
{% load i18n %}

{% block title %}{{ block.super }} {% translate "Delete lesson" %}{% endblock %}

{% block form_title %}{% translate "Delete the lesson" %}{% endblock %}

{% block form_alert %}
    <div class="alert alert-danger" role="alert">
        <h5 class="alert-heading">{% translate "Warning" %} <i class="fas fa-exclamation-triangle"></i></h5>
        <p>
            <span class="font-6">
                {% translate "Are you sure you want to delete this lesson?" %}
            </span>
        </p>
        <hr>
        <p class="mb-0">
            {% translate "This data will be destroyed and you won't be able to retrieve it." %}
        </p>
    </div>
{% endblock %}

{% block form_body %}
    <form method="post">{% csrf_token %}
        <input class="btn site-btn mb-3 w-100 font-5" type="submit" value="{% translate "Delete" %}">
    </form>
{% endblock %}

{% block back_url %}
    <a href="{% url 'reservation_management:lesson-detail' lesson.pk %}" class="font-6 site-blue-text">
        <i class="fas fa-chevron-left mr-2"></i>
        {% translate "Back to lesson" %}
    </a>
{% endblock %}

app/reservation_management/templates/reservation_management/lesson_detail.html
{% extends '../../../templates/base.html' %}
{% load i18n %}
{% load app_filters %}

{% block title %}{{ block.super }} {% translate "Lesson" %}{% endblock %}

{% block content %}
    <div class="site-box">
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <div class="row">
                    <div class="col d-flex flex-column">
                        <span class="text-muted font-5">{{ lesson.day|get_day_from_int }}</span>
                        <span class="h2 site-color logo-font">{{ lesson.classroom.name }}</span>
                        <span class="font-6">{{ lesson.classroom.building.name }}</span>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'reservation_management:lesson-update' lesson.pk %}"
                           class="site-link no-decoration">
                            <i class="fas fa-pen mt-2 mr-3"></i>
                        </a>
                        <a href="{% url 'reservation_management:lesson-delete' lesson.pk %}" class="site-link no-decoration">
                            <i class="fas fa-trash text-danger"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <ul>
                    <li>{% translate "Start at " %}{{ lesson.start_time }}</li>
                    <li>{% translate "End at " %}{{ lesson.end_time }}</li>
                </ul>
                <p>

                </p>
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between align-items-center">
                <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 site-blue-text">
                    <i class="fas fa-chevron-left mr-2"></i>
                    {% translate "Your lessons" %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

app/reservation_management/templates/reservation_management/lesson_list.html
{% extends 'reservation_management/base/base/base_list.html' %}
{% load static %}
{% load i18n %}
{% load app_filters %}

{% block title %}
    {{ block.super }} {% translate 'My lessons' %}
{% endblock %}

{% block list_title %}
    {% translate 'Your lessons' %}
{% endblock %}

{% block list_button %}
    <div class="row justify-content-center">
        <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-end">
            <a href="{% url "reservation_management:lesson-add" %}"
               class="btn site-btn font-5" style="width: auto !important;">
                <i class="fas fa-plus"></i>
            </a>
        </div>
    </div>
{% endblock %}

{% block list_body %}
    {% for lesson in lesson_list %}
        <a href="{% url 'reservation_management:lesson-detail' lesson.pk %}"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/calendar.png' %}" alt="cal" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{{ lesson.classroom }} {{ lesson.start_time }}
                        - {{ lesson.end_time }}</h6>
                    <p class="mb-0 opacity-75">
                        {{ lesson.classroom.building }}</p>
                </div>
                <small class="opacity-50 text-nowrap">{{ lesson.day|get_day_from_int }}</small>
            </div>
        </a>
    {% empty %}
        <a href="{{ reservation.link }}"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/empty.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-2">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{% translate "No lesson here, insert your lessons!" %}</h6>
                    <p class="mb-0 opacity-75">
                        {% blocktranslate %}
                            Click the <strong>button</strong> and add them!
                        {% endblocktranslate %}
                    </p>
                </div>
                <small class="opacity-50 text-nowrap"></small>
            </div>
        </a>
    {% endfor %}
{% endblock %}

{% block list_nav_button %}
    <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-between align-items-center">
        <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
            <i class="fas fa-chevron-left mr-2"></i>
            {% translate "Your reservations" %}
        </a>
    </div>
{% endblock %}

app/reservation_management/templates/reservation_management/lesson_update.html
{% extends '../../../templates/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} {% translate "Update lesson" %}{% endblock %}

{% block form_title %}{% translate "Update lesson information" %}{% endblock %}

{% block form_body %}
    {% crispy form %}
{% endblock %}

{% block back_url %}
    <a href="{% url 'reservation_management:lesson-detail' lesson.pk %}" class="font-6 site-blue-text">
        <i class="fas fa-chevron-left mr-2"></i>
        {% translate "Back to lesson" %}
    </a>
{% endblock %}

app/reservation_management/templates/reservation_management/log_list.html
{% extends '../../../templates/base_admin.html' %}

{% block title %}Logs{% endblock %}
{% block page_title %}Logs{% endblock %}

{% block items %}
    <span class="font-6">{{ item.date }}</span>
    <span>Execution time: {{ item.execution_time }}</span>
    <span>Lessons: {{ item.lessons }}</span>
    <span>Users: {{ item.users }}</span>
    <span>Average exec per user: {{ item.average_user_execution_time }}</span>
    <span>Average exec per lesson: {{ item.average_lesson_execution_time }}</span>
{% endblock %}

app/reservation_management/templates/reservation_management/reservation_list.html
{% extends 'reservation_management/base/base/base_list.html' %}
{% load static %}
{% load i18n %}
{% load app_filters %}

{% block title %}
    {{ block.super }} {% translate 'My lessons' %}
{% endblock %}

{% block list_title %}
    {% translate "Your reservations" %}
{% endblock %}

{% block list_button %}
    {% if user.green_pass_link is not None %}
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-end">
                <a href="{{ user.green_pass_link }}" target="_blank" class="btn green-btn font-5">
                    <i class="fas fa-passport mr-2"></i>
                    {% translate "Green Pass" %}
                </a>
            </div>
        </div>
    {% else %}
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-end">
                <a href="{% url 'user_management:green-pass-add' %}" class="btn green-btn font-5">
                    <i class="fas fa-passport mr-2"></i>
                    {% translate "Add your Green Pass" %}
                </a>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block list_body %}
    {% for reservation in reservation_list %}
        <a href="{{ reservation.link }}" target="_blank"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/reservation.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{{ reservation.lesson.classroom }} {{ reservation.lesson.start_time }}
                        - {{ reservation.lesson.end_time }}</h6>
                    <p class="mb-0 opacity-75">
                        {{ reservation.lesson.classroom.building }}</p>
                </div>
                <small class="opacity-50 text-nowrap">{{ reservation.lesson.day|get_day_from_int }}</small>
            </div>
        </a>
    {% empty %}
        <a href="{{ reservation.link }}"
           class="list-group-item list-group-item-action d-flex gap-3 py-3"
           aria-current="true">
            <img src="{% static 'img/empty.png' %}" alt="res" width="32" height="32"
                 class="flex-shrink-0 mr-3">
            <div class="d-flex gap-2 w-100 justify-content-between">
                <div>
                    <h6 class="mb-0">{% translate "No reservation made, insert your lessons!" %}</h6>
                    <p class="mb-0 opacity-75">
                        {% blocktranslate %}
                            Go to <strong>Your lessons</strong> and add them!
                        {% endblocktranslate %}
                    </p>
                </div>
                <small class="opacity-50 text-nowrap"></small>
            </div>
        </a>
    {% endfor %}
{% endblock %}

{% block extra_content %}
    {% include '../../../templates/whats_new_modal.html' %}
    {% if not user.feedback %}
        <div class="row justify-content-center align-items-center mt-3 mb-5">
            <div id="user-feedback-box" class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex column-flex align-items-center justify-content-center">
                <span class="font-6">
                    {% translate "Are your reservations correct?" %}
                </span>
                <div class="mt-3 w-100 d-flex justify-content-center align-items-center">
                    <button id="feedback-response-yes" class="btn btn-outline-success mr-3 font-size-80 w-25">
                        {% translate "Yes" %}
                    </button>
                    <button id="feedback-response-no" class="btn btn-outline-danger font-size-80 w-25">
                        {% translate "No" %}
                    </button>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block list_nav_button %}
    <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex justify-content-end">
        <a href="{% url 'reservation_management:lesson-list' %}" class="font-6 site-blue-text">
            {% translate "Your lessons" %}
            <i class="fas fa-chevron-right ml-2"></i>
        </a>
    </div>
{% endblock %}

{% block manager_tools %}
    {% if user.is_manager %}
        <div class="row justify-content-center mt-5 px-3">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex flex-column border p-4">
                <span class="h4 font-6 logo-font">Administration</span>
                <a href="{% url 'user_management:list' %}" class="site-link site-color font-6">
                    Users
                </a>
                <a href="{% url 'reservation_management:log-list' %}" class="site-link site-color font-6">
                    Logs
                </a>
                <a href="{% url 'reservation_management:feedback-list' %}" class="site-link site-color font-6">
                    Feedbacks
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block extra_javascript %}
    <script type="text/javascript">
        $(function () {
            $("#feedback-response-yes").on('click', function () {
                send_feedback(1, $(this));
            });

            $("#feedback-response-no").on('click', function () {
                send_feedback(0, $(this));
            });

            {% if user.whats_new %}
                $('#whats-new-modal').modal('show');
            {% endif %}
        });
    </script>
    {% include 'reservation_management/reservation_ajax.html' %}
{% endblock %}