app/reservation_management/urls.py
from django.urls import path
from app.reservation_management import views

app_name = 'reservation_management'

urlpatterns = [
    path('', views.ReservationListView.as_view(), name='reservation-list'),
    path('lesson/add', views.LessonAddView.as_view(), name='lesson-add'),
    path('lesson/list', views.LessonListView.as_view(), name='lesson-list'),
    path('lesson/<int:pk>/detail', views.LessonDetailView.as_view(), name='lesson-detail'),
    path('lesson/<int:pk>/update', views.LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/<int:pk>/delete', views.LessonDeleteView.as_view(), name='lesson-delete'),
    path('log-list', views.LogListView.as_view(), name='log-list'),
    path('feedback-list', views.FeedbackListView.as_view(), name='feedback-list'),
    path('send-feedback', views.ajax_send_feedback, name='send-feedback'),
    path('whats-new-confirm', views.ajax_whats_new_confirm, name='whats-new-confirm'),
]

app/reservation_tool_base_folder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app.reservation_tool_base_folder.views import HomepageView, HelpView

urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('help', HelpView.as_view(), name='help'),
    path('user/', include('user_management.urls')),
    path('reservation/', include('reservation_management.urls')),
]

if settings.ADMIN_ENABLED:
    urlpatterns.append(
        path('admin/', admin.site.urls)
    )

app/user_management/urls.py
from django.urls import path
from app.user_management import views
from django.contrib.auth import views as auth_views

app_name = 'user_management'

urlpatterns = [
    path('login', views.LoginUserView.as_view(), name='login'),
    path('registration', views.RegistrationView.as_view(), name='registration'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('list', views.UserListView.as_view(), name='list'),
    path('ajax-check-username-exists', views.ajax_check_username_exists, name='ajax-check-username-exists'),
    path('ajax-check-email', views.ajax_check_email, name='ajax-check-email'),
    path('email/verification_needed', views.EmailVerificationNeededView.as_view(), name='email-verification-needed'),
    path('email/verified', views.EmailVerifiedView.as_view(), name='email-verified'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
    path('ajax-check-username-is-correct', views.ajax_check_username_is_correct, name='ajax-check-username-is-correct'),
    path('ajax-check-unimore-credentials', views.ajax_check_unimore_credentials, name='ajax-check-unimore-credentials'),
    path('settings', views.SettingsView.as_view(), name='settings'),
    path('delete', views.UserDeleteView.as_view(), name='delete'),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('cookie-policy', views.CookiePolicyView.as_view(), name='cookie-policy'),
    path(
        'update-unimore-credentials',
        views.UserUpdateUnimoreCredentialsView.as_view(),
        name='update-unimore-credentials'
    ),
    path('greenpass-add', views.UserGreenPassAddView.as_view(), name='green-pass-add'),
    path('greenpass-delete', views.UserGreenPassDeleteView.as_view(), name='green-pass-delete'),
    path('general-settings', views.UserGeneralSettingsView.as_view(), name='general-settings'),

]

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Cookie consent Javascript -->
    <script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="b02afbbd-fd14-425f-b4e0-26d7e488bbf8"
            data-blockingmode="auto" type="text/javascript"></script>

    <!-- FontAwesome CSS -->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=ZCOOL+KuaiLe&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/css/bootstrap-select.min.css"
          integrity="sha256-jwJEU4p1YdtymLFwAjYfam5Pj5NOnylms63k7LYQ9Jk=" crossorigin="anonymous"/>


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">

    {% block extra_css %} {% endblock %}

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/ninja.png' %}">

    <title>{% block title %}ReservationNinja |{% endblock %}</title>
</head>

<body>

<div id="site-main-page" class="container-fluid mt-3">
    {% if user.is_authenticated %}
        <div class="row justify-content-end px-4">
            <a href="{% url 'user_management:settings' %}" class="path-link mr-2">
                <i class="fas fa-cog"></i>
            </a>
            <a href="{% url 'user_management:logout' %}" class="path-link font-6">
                Logout <i class="fas fa-sign-out-alt ml-2"></i>
            </a>
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/js/bootstrap-select.js"
        integrity="sha256-GwAMtRKq8ocZyBdgm1wX+tzd2/nDbb2UGulIdqOItiU=" crossorigin="anonymous"></script>

<!-- Optional JavaScript -->
<script src="{% static 'js/site_javascript.js' %}"></script>
{% block extra_javascript %}{% endblock %}
</body>
</html>

app/templates/base_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="site-box">
        <div class="row h-100 w-100 ml-0 justify-content-center">
            <div id="lesson-column"
                 class="col-xl-3 col-lg-5 col-md-9 col-12 d-flex align-items-center justify-content-center p-0">
                <form method="POST" class="w-100">
                    <h2 class="mb-5 font-7 logo-font site-color">
                        {% block form_title %}{% endblock %}
                    </h2>
                    {% block form_alert %}
                    {% endblock %}
                    <div>
                        {% block form_body %}
                        {% endblock %}
                        <div class="row justify-content-start mt-4">
                            <div class="col d-flex justify-content-between align-items-center mt-3">
                                {% block back_url %}{% endblock %}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/footer.html
{% load static %}
{% load i18n %}

<div id="footer" class="mt-5 d-flex justify-content-between align-items-center">
    <div class="d-flex justify-content-start align-items-center p-4">
        <img src="{% static "img/ninja.png" %}"
             class="picture-xxs mr-2"
             alt="Ninja icon"
        >
        <span class="logo-font">Reservation Ninja</span>
    </div>
    <div class="d-flex justify-content-end align-items-center p-4">
        <a href="{% url 'help' %}" class="site-link font-6">
            <span>
                {% translate "Help" %}
            </span>
        </a>
    </div>
</div>

app/templates/help.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="site-box mt-5">
        <div class="row justify-content-center">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <h2 class="logo-font site-color">
                    {% translate "Help" %}
                </h2>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                <p>
                    {% blocktranslate %}
                        If you have some doubt or you want to report an issue,
                        write to this email:
                        <span class="font-6 site-color">reservationtoolninja@gmail.com</span>.
                    {% endblocktranslate %}
                </p>
                <p class="font-6">
                    {% blocktranslate %}
                        Check out our privacy policies
                    {% endblocktranslate %}
                </p>
                <ul>
                    <li>
                        <a href="{% url 'user_management:cookie-policy' %}"
                           target="_blank"
                           class="font-6 site-link site-color">
                            {% translate "Cookie policy" %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'user_management:privacy-policy' %}"
                           target="_blank"
                           class="font-6 site-link site-color">
                            {% translate "Privacy policy" %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-xl-3 col-lg-5 col-md-9 col-12">
                {% if user.is_authenticated %}
                    <a href="{% url 'reservation_management:reservation-list' %}" class="font-6 site-blue-text">
                        <i class="fas fa-chevron-left ml-2"></i>
                        {% translate "Back home" %}
                    </a>
                {% else %}
                    <a href="{% url 'home' %}" class="font-6 site-blue-text">
                        <i class="fas fa-chevron-left ml-2"></i>
                        {% translate "Back home" %}
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}